### ISSUE TITLE
In the 'modern' paperdoll, there's no way to get to the special abilities

### ISSUE THREAD

**Issue by Flydawg** [bittiez/ClassicUO#108]
**Describe the bug**
In the original paperdoll, there is a purple book at the lower right, that when double-clicked shows the primary & secondary abilities for the current weapon.  The 'modern' paperdoll doesn't seem to have any way to get to this information.

**To Reproduce**
1. In options, switch to using the modern paperdoll
2. No way to access special moves

**Expected behavior**
I would have expected access to most likely be through the menu

**Screenshots**

**Shard**
 - Name of the shard: UOAlive

**Information (please complete the following information):**
 - OS: Win10
 - ClassicUO Version: 0.1.11.0 is what the screen says, but it's v2.9.x I believe
 - [ ] Using DEV Version? No
 - Launcher: I just click on the .exe.  RE is my main plugin

**Additional context**
 - How many clients do you run in parallel: None
 - Screen Resolution: 2560x1440

**Comment by bittiez** [comment]
Fixed for the next update 
![image](https://user-images.githubusercontent.com/3859393/232254398-f48337f6-ae7b-43b9-a791-1ee8fd9385cc.png)

Thanks for the report 👍
