### ISSUE TITLE
World Map menu not working

### ISSUE THREAD

**Issue by Flydawg** [bittiez/ClassicUO#122]
**Describe the bug**
When I right-click on the world map, the menu doesn't come up

**To Reproduce**
1. Show the world map (mine is shown, and I have no way to hide it)
2. Right-click on the world map

**Expected behavior**
I expected a menu to appear where I could set Free View, access Marker Manager, etc.

**Screenshots**

**Shard**
 - Name of the shard: UOAlive

**Information (please complete the following information):**
 - OS: Win10
 - ClassicUO Version: 0.1.11.0 / 2.13.x
 - [ ] Using DEV Version?
 - Launcher: Starting the client via ClassicUO.exe

**Additional context**
 - How many clients do you run in parallel: None
 - Screen Resolution: 2560x1440

This worked up until 2.12 I think.  I don't use the menu that often.  When it didn't work today, I downloaded the latest version, and the menu still doesn't work.  Is there a config option that disables the menu that I've somehow set?  It zooms, switches areas, loads markers just fine.  I just can't get the menu to come up.  I have restarted the client.  I have not rebooted the PC.

**Comment by Flydawg** [comment]
I've since rebooted the computer, and updated Razor Enhanced to the latest version.  No change.

**Comment by bittiez** [comment]
You'll just need to single click the map once, then right click should work again. This will be fixed in the next update, you're more than welcome to build from the dev branch if you don't want to wait though.

**Comment by Flydawg** [comment]
Just tried it.  That doesn’t work on the version I have (2.13.2).  Fyi...

**Comment by bittiez** [comment]
Okay, it works for me so I'm not sure why it wouldn't work for you but I will try to push this update out early for you 👍

**Comment by bittiez** [comment]
In fact, I will actually get an update pushed out now, then do another one later this week for other planned changes this week 👍
