### ISSUE TITLE
2nd log in to the client causes it to hang

### ISSUE THREAD

**Issue by Flydawg** [bittiez/ClassicUO#141]
**Describe the bug**
I start the client, and log into a character.  Play for a bit.  Then logout and login on a different character.  The client either hangs on the Loading Character screen, or crashes.  This has always been using the same account.  Just logging in and out is not enough to cause the behavior.  You have to actually do some things on the first character.  Usually my char is a bard/tamer, so maybe it's some of his abilities that cause it.  So far, I've been unable to run the bug down further.  I don't expect that this is enough to fix it, but I wanted to let you know, and if I can come up w/ a better/tighter set of steps to repro, I'll update this.

**To Reproduce**
1. Login on character 'A'
2. Play for a bit
3. Log out
4. Login on character 'B'

**Expected behavior**
Should login character 'B' and not hang/crash

**Screenshots**

**Shard**
 - Name of the shard: UOAlive

**Information (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.2965]
 - ClassicUO Version: 7.0.98.1
 - [ ] Using DEV Version? No
 - Launcher: dbl-click .exe.  Plugin is Razor Enhanced

**Additional context**
 - How many clients do you run in parallel: None
 - Screen Resolution: 2560x1440

**Comment by Jascen** [comment]
Just as a heads up, I'm playing on Ultima Adventures and don't have this issue.

**Comment by Flydawg** [comment]
So far, it feels like a memory leak.  I have to have been logged into the first char and doing something for a while.  Just logging in and sitting, then switching chars doesn’t cause it.

**Comment by bittiez** [comment]
A few others helped diagnose this in discord a while back, you should be able to download the test build from our discord -> https://discord.gg/SqwtB5g95H

It may be a while before it's released on github because this project has taken a backseat for me
