### ISSUE TITLE
OSI is updating artwork, some servers are looking for an updated client

### ISSUE THREAD

**Issue by Flydawg** [bittiez/ClassicUO#145]
UOAlive is looking for at least 7.0.99.0.  It's been talked about that OSI is adding some new artwork.  Is there any chance we can get the client updated to the latest versions?

![image](https://github.com/bittiez/ClassicUO/assets/61070070/8c84b637-7345-4cb4-9283-572f681b9090)

**Comment by bittiez** [comment]
The client is provided by your server, CUO and TUO are more like a Layer on top of your client. Simply update your UO client, there are many guides for this online
