### ISSUE TITLE
Grid item name

### ISSUE THREAD

**Issue by ilovebittiez** [bittiez/ClassicUO#22]
Love the grid backpacks, is there a way to show item name on mouse hover? my Runuo has expansion set to None, so item name doesnt show up whenever i mouse hover the items, not sure if that can be done client side, btw the gump tool tips does work?

**Comment by bittiez** [comment]
Would you mind posting a pic for me?

**Comment by ilovebittiez** [comment]
https://ibb.co/LP65z3b

mouse over an item, it doesnt, the item name doesnt pop up, i have to click, my expansion is set to None

**Comment by bittiez** [comment]
So I disabled the single-click to show item name because I couldn't get it to appear above the item, it would appear in weird places on the screen but I will see what I can do to get it working 👍

**Comment by bittiez** [comment]
Well, this is about as good as I'm going to be able to get it for the time being, the name will pop up above the container top-left
![image](https://user-images.githubusercontent.com/3859393/224492175-63ac1354-9f1c-41c8-b750-e48ebda85fca.png)

**Comment by bittiez** [comment]
Somewhat Fixed with #25

**Comment by ilovebittiez** [comment]
thank you Bittiez
